# application properties should be here
quarkus.http.port=18080

mp.messaging.incoming.prices.connector=smallrye-kafka
mp.messaging.outgoing.prices-out.connector=smallrye-kafka

mp.messaging.incoming.prices.topic=mytopic
mp.messaging.outgoing.prices-out.topic=mytopic

quarkus.rest-client.greeting.url=stork://greeting-service
#quarkus.rest-client.greeting.url=http://localhost:18080

quarkus.stork.greeting-service.service-discovery.type=static
quarkus.stork.greeting-service.service-discovery.address-list=localhost:18080
quarkus.stork.greeting-service.load-balancer.type=round-robin