infinispan.client.hotrod.connect_timeout=1000
infinispan.client.hotrod.socket_timeout=2000
infinispan.client.hotrod.max_retries=0
infinispan.client.hotrod.server_failure_timeout=5000
infinispan.client.hotrod.connection_pool.max_active=2
infinispan.client.hotrod.connection_pool.max_wait=1000
infinispan.client.hotrod.connection_pool.max_pending_requests=5
